### ISSUE TITLE
test on k8s deployment

### ISSUE THREAD

**Issue by scottyhq** [scottyhq/jupyter-cloud-scoped-creds#1]
so far this is was only tested locally with running `jupyter server` then going to `http://127.0.0.1:8889/api/cloudcreds/aws` which worked! 

cc @yuvipanda

**Comment by scottyhq** [comment]
Currently not working with hub logs showing: 

> [W 2022-07-22 15:51:00.096 JupyterHub base:1570] Content security violation: {"csp-report":{"document-uri":"https://hub.aws-uswest2-binder.pangeo.io/hub/api/cloudcreds/aws","referrer":"","violated-directive":"style-src-attr","effective-directive":"style-src-attr","original-policy":"frame-ancestors 'self'; report-uri /hub/security/csp-report; default-src 'none'","disposition":"enforce","blocked-uri":"inline","line-number":1,"source-file":"https://hub.aws-uswest2-binder.pangeo.io/hub/api/cloudcreds/aws","status-code":404,"script-sample":""}}

**Comment by scottyhq** [comment]
Trying to understand https://jupyter-server.readthedocs.io/en/latest/operators/security.html?highlight=authorization#authentication-and-authorization and if this needs both `@web.authenticated` and `@authorized` ... and therefore `jupyter_server>2`

**Comment by yuvipanda** [comment]
@scottyhq what is the curl command you are using? Are you passing the JupyterHub token?

**Comment by scottyhq** [comment]
The above was a red herring, I needed to print out the stderr to see that the cmd was poorly formed! 
https://github.com/scottyhq/jupyter-cloud-scoped-creds/blob/f9e30953f20bc3fb6971077f847c7021b88c728a/jupyter_cloud_scoped_creds/__init__.py#L31 

It's working! Tested on https://aws-uswest2-binder.pangeo.io/v2/gh/scottyhq/pageodev-binder-image/master?urlpath=lab

**Comment by yuvipanda** [comment]
Yay, awesome! We should probably return stderr output if the exit code isn't 0 of the process
